#!/usr/bin/env bash
# This script installs nginx on a server that listens on port 80
# returns a page with the string Hello world

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/
              sites-available/default
sudo service nginx restart
echo "Hello World!" | sudo tee /var/www/html/index.html
