#!/usr/bin/env bash
# This script installs nginx on a server that listens on port 80
# returns a page with the string Hello world

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
