#!/usr/bin/env bash
# This script installs nginx on a server that listens on port 80
# returns a page with the string Hello world

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i '/server_name _;/a \
	error_page 404 /404.html;\n\
	location = /404.html {\n\
		root /usr/share/nginx/html;\n\
		internal;\n\
	}' /etc/nginx/sites-available/default

sudo service nginx restart
