#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
# Make sure that your servers are configured with the right hostnames:
# [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.


sudo apt-get -y update

sudo apt-get -y install haproxy

sudo service haproxy start
sudo cp -a /etc/haproxy/haproxy.cfg{,.original}

echo '
frontend haproxy_balancer
	bind *:80
	mode http
	default_backend myservers

backend myservers
	balance roundrobin
	server 327055-web-01 100.26.209.142:80 check
	server 327055-web-02 54.158.214.70:80 check' |
sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
