#!/usr/bin/env bash
# A Bash script with the minimum number of commands to enable Ubuntu 
# container’s Nginx installation to listen on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
