#!/usr/bin/env bash
# Install and configure ufw firewall

sudo su
apt-get upgrade
apt-get install ufw
ufw default allow outgoing
ufw default deny incoming
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw enable
ufw status
