#!/usr/bin/env bash
# configure your machine so that you can connect to a server without typing
# a password. Share your SSH client configuration in your answer file.

Host server01
  HostName 100.25.140.208
  User ubuntu
  IdentityFile ~/.ssh/school
  PasswordAuthentication no
